openapi: 3.0.1
info:
  title: 3d store-trigger
  description: Ingesting and exporting 3d model to S3/NFS
  version: 1.0.0
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

paths:
  /jobs/ingestion:
    post:
      operationId: createModel
      tags:
        - jobs
      summary: creates a new job and invokes a new model ingestion flow
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/payload'
      responses:
        201:
          description: created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/createResponse'
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        '5XX':
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
  /jobs/delete:
    post:
      operationId: deleteModel
      tags:
        - jobs
      summary: creates a new delete job and invokes a model deleting flow
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/delete-request'
      responses:
        '201':
          description: created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/createResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        5XX:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
components:
  schemas:
    error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
    payload:
      type: object
      description: 3d model payload
      required:
        - modelId
        - pathToTileset
        - tilesetFilename
        - metadata
      properties:
        modelId:
          type: string
          description: Model identifier
          example: 'a2234fdf'
        pathToTileset:
          type: string
          description: path to tileset
          example: 'NewYork'
        tilesetFilename:
          type: string
          description: Model tileset filename
          example: 'tileset.json'
        metadata:
          $ref: './Schema/3dCatalog/3dMetadata.yaml#/components/schemas/ingestion-payload'
      additionalProperties: false
    createResponse:
      type: object
      description: The ingestion response
      required:
        - jobId
        - status
      properties:
        status:
          type: string
          enum:
            - Completed
            - In-Progress
            - Pending
            - Failed
            - Expired
            - Aborted
        jobId:
          type: string
          description: job id
    deleteRequest:
      type: object
      description: 3d tiles delete requestBody
      required:
        - modelId
        - pathToTileset
        - modelName
      properties:
        modelId:
          type: string
          nullable: true
          default: null
          example: a2234fdf
          description: ID of product
        pathToTileset:
          type: string
          description: path to tileset
          example: NewYork
        modelName:
          type: string
          maxLength: 50
          description: Name of product
