{{- $releaseName := .Release.Name -}}
{{- $chartName := include "3d-job-syncer.name" . -}}
{{- $cloudProviderFlavor := include "3d-job-syncer.cloudProviderFlavor" . -}}
{{- $cloudProviderDockerRegistryUrl := include "3d-job-syncer.cloudProviderDockerRegistryUrl" . -}}
{{- $cloudProviderImagePullSecretName := include "3d-job-syncer.cloudProviderImagePullSecretName" . -}}
{{- $imageTag := include "ts-server-boilerplate.tag" . -}}
{{- if .Values.enabled -}}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ $releaseName }}-{{ $chartName }}-job-syncer
  labels:
    app: {{ $chartName }}
    component: {{ $chartName }}
    environment: {{ include "3d-job-syncer.environment" . }}
    release: {{ $releaseName }}
    {{- include "3d-job-syncer.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.cron.schedule | quote }}
  successfulJobsHistoryLimit: {{ .Values.cron.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.cron.failedJobsHistoryLimit }}
  concurrencyPolicy: {{ .Values.cron.concurrencyPolicy }}
  jobTemplate:
    spec:
      template:
        spec:
          {{- if $cloudProviderImagePullSecretName }}
          imagePullSecrets:
            - name: {{ $cloudProviderImagePullSecretName | quote }}
          {{- end }}
          restartPolicy: {{ .Values.cron.restartPolicy }}
          containers:
            - name: {{ $releaseName }}-{{ $chartName }}-deployment
              {{- with .Values.image }}
              image: {{ $cloudProviderDockerRegistryUrl }}{{ .repository }}:{{ $imageTag }}
              {{- end }}
              envFrom:
                - configMapRef:
                    name: {{ $releaseName }}-{{ $chartName }}-configmap
              {{- if .Values.resources.enabled }}
              resources:
                {{- toYaml .Values.resources.value | nindent 16 }}
              {{- end }}
{{- end -}}
