global:
  cloudProvider: {}
  tracing: {}
  metrics: {}
  environment: {}

enabled: true
environment: development
replicaCount: 1
initialDelaySeconds: 60
nodePort: 30030 #for minikube deployment only
resetOnConfigChange: true

cloudProvider:
  dockerRegistryUrl: my-registry-url.io
  imagePullSecretName: 'my-registry-secret'
  flavor: openshift

caSecretName: ''
caPath: '/usr/local/share/ca-certificates'
caKey: 'ca.crt'

image:
  repository: store-sync-3d
  tag: 'latest'

env:
  port: 8080
  targetPort: 8080
  protocol: TCP
  logLevel: info
  logPrettyPrintEnabled: false
  responseCompressionEnabled: true
  requestPayloadLimit: 1mb
  tracing:
    enabled: false
    url: http://localhost:55681/v1/trace
  metrics:
    enabled: false
    url: http://localhost:55681/v1/metrics

  common:
    job:
      type: job_type
    task:
      type: taskType
      batches: 100
      maxAttempts: 3000
    jobManager:
      url: job_manager_url
    heartbeat:
      url: heartbeat_url
      waitTime: 3000
    catalog:
      url: catalog_url
      nginxUrl: nginx_url
    providers:
      source: S3
      destination: S3
    worker:
      waitTime: 3000
    jobSyncer:
      scheduleTime: "* * * * * *"
    S3:
      source:
        access_key: access_key
        secret_access_key: secret_access_key
        host: host
        bucket: bucket
        ssl_enabled: false
      destination:
        access_key: access_key
        secret_access_key: secret_access_key
        host: host
        bucket: bucket
        ssl_enabled: false
    NFS:
      source:
        pv_path: pv_path
      destination: 
        pv_path: pv_path



resources:
  enabled: true
  value:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

route:
  enabled: true
  path: /
  timeout:
    enabled: false # defaults to 30s by openshift
    duration: 60s # supported units (us, ms, s, m, h, d)
